include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    invalid_use_of_protected_member: error
linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    prefer_single_quotes: true
